### ISSUE TITLE
此项目，可以直接接入现有的vue项目吗？

### ISSUE THREAD

**Issue by dbl520** [netease-im/NIM_Web_Demo_H5#17]
npm run server
npm ERR! missing script: server

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-08-09T11_12_59_164Z-debug.log

D:\VUE\dzjj-gw>node server
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'ejs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\VUE\dzjj-gw\server.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by eyea** [comment]
哈哈  正在写对应demo中 😸

**Comment by dbl520** [comment]
> 哈哈 正在写对应demo中 😸
